parser: "@typescript-eslint/parser"
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "@typescript-eslint"
  - "prettier"
rules:
  no-sequences: off
